# 1 train, 0 test
python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path /data/pcw_workspace/Quant_snp/dataset/DAN_Dataset_11_07/Input/ \
  --model_id TimeMixer_Apr10_96_24 \
  --model TimeMixer \
  --data SNP500 \
  --batch_size 1024 \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --label_len 0 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 12 \
  --dec_in 12 \
  --c_out 12 \
  --des 'Exp' \
  --itr 1 \
  --d_model 16 \
  --d_ff 32 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2